import Link from "next/link";
import { ArrowUpRight, Download, Link as LinkIcon, Mail } from "lucide-react";
import { notes, projects, topics, work, writing } from "@/lib/content";
export default function Home() { return <>
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Vancouver, Canada · Open to thoughtful conversations</p><h1>Building reliable systems—and a life of <em>useful ideas.</em></h1><p className="hero-intro">I’m Zee, a Platform / DevOps Engineer working across cloud infrastructure, reliability, automation, and developer experience. This is where I collect the work, questions, and experiments that shape how I think.</p><div className="hero-links"><a href="https://www.linkedin.com/"><LinkIcon size={17} /> LinkedIn</a><a href="https://github.com/"><LinkIcon size={17} /> GitHub</a><Link href="/resume"><Download size={17} /> Résumé</Link><a href="mailto:hello@example.com"><Mail size={17} /> Email</a></div></div><div className="portrait-frame" aria-label="Portrait placeholder for Zee"><div className="portrait-mark"><span>Z</span></div><p>Portrait</p><small>Replace with your headshot</small></div></section>
  <section className="section shell" id="work"><div className="section-heading"><p className="eyebrow">01 / Selected work</p><h2>Systems that leave things better.</h2><Link href="/work">All work <ArrowUpRight size={15} /></Link></div><div className="work-list">{work.map((item, index) => <Link href={`/work#${item.slug}`} className="work-row" key={item.slug}><span className="row-index">0{index + 1}</span><div><h3>{item.title}</h3><p>{item.summary}</p><ul>{item.technologies.slice(0, 4).map((tech) => <li key={tech}>{tech}</li>)}</ul></div><ArrowUpRight className="row-arrow" size={20} /></Link>)}</div></section>
  <section className="section shell split-section"><div><div className="section-heading compact"><p className="eyebrow">02 / Latest writing</p><Link href="/writing">View all <ArrowUpRight size={15} /></Link></div><div className="writing-list">{writing.map((item) => <Link href={`/writing/${item.slug}`} key={item.slug} className="writing-row"><div className="writing-meta"><span>{item.category}</span><span>{item.readTime}</span></div><h3>{item.title}</h3><p>{item.description}</p><time>{item.date}</time></Link>)}</div></div><aside className="exploring"><p className="eyebrow">03 / Currently exploring</p><h2>What has my attention now.</h2><div className="topic-cloud">{topics.map((topic) => <Link key={topic} href={`/topics/${topic.toLowerCase().replaceAll(" ", "-")}`}>{topic}</Link>)}</div><Link className="text-link" href="/now">See what I’m doing now <ArrowUpRight size={15} /></Link></aside></section>
  <section className="manifesto shell"><p className="eyebrow">A personal digital home</p><blockquote>“Not only a résumé, but a record of things I build, learn, question, and explore.”</blockquote><p>Professional credibility comes first. Keep looking and you’ll find experiments, notes from the mat, investment thinking, and an evolving philosophy of useful work.</p></section>
  <section className="section shell lab-preview"><div className="section-heading"><p className="eyebrow">04 / From the lab</p><h2>Small bets and unfinished things.</h2><Link href="/projects">Enter the lab <ArrowUpRight size={15} /></Link></div><div className="project-grid">{projects.slice(0, 3).map((project) => <Link href="/projects" key={project.title} className="project-card"><span className="project-status">{project.status}</span><h3>{project.title}</h3><p>{project.summary}</p><small>{project.tech}</small></Link>)}</div><div className="latest-note"><span>{notes[0].date}</span><p>Latest note · <Link href="/notes">{notes[0].title}</Link></p></div></section>
</>; }
