import Link from "next/link";
import { ArrowUpRight, Download, Link as LinkIcon, Mail } from "lucide-react";
import { notes, projects, topics, work, writing } from "@/lib/content";
export default function Home() { return <>
  <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Vancouver, British Columbia · 15+ years in engineering</p><h1>Building software.<br />Engineering <em>reliable platforms.</em></h1><p className="hero-intro">I’m Zee Caniago, a Staff Software & Platform Engineer with 15+ years across software development, cloud infrastructure, and production operations. At HP, I build automation for SaaS platforms, from provisioning and deployment to secrets management and security controls.</p><div className="hero-links"><a href="https://www.linkedin.com/in/zeecaniago"><LinkIcon size={17} /> LinkedIn</a><a href="https://github.com/zeecaniago"><LinkIcon size={17} /> GitHub</a><Link href="/resume"><Download size={17} /> Résumé</Link><a href="mailto:zee.caniago@gmail.com"><Mail size={17} /> Email</a></div></div><div className="portrait-frame" aria-label="Zee Caniago, Staff Software and Platform Engineer"><div className="portrait-mark"><span>ZC</span></div><p>Zee Caniago</p><small>Software &amp; Platform Engineer</small></div></section>
  <section className="section shell" id="work"><div className="section-heading"><p className="eyebrow">01 / Selected work</p><h2>Systems that leave things better.</h2><Link href="/work">All work <ArrowUpRight size={15} /></Link></div><div className="work-list">{work.map((item, index) => <Link href={`/work#${item.slug}`} className="work-row" key={item.slug}><span className="row-index">0{index + 1}</span><div><h3>{item.title}</h3><p>{item.summary}</p><ul>{item.technologies.slice(0, 4).map((tech) => <li key={tech}>{tech}</li>)}</ul></div><ArrowUpRight className="row-arrow" size={20} /></Link>)}</div></section>
  <section className="section shell split-section"><div><div className="section-heading compact"><p className="eyebrow">02 / Latest writing</p><Link href="/writing">View all <ArrowUpRight size={15} /></Link></div><div className="writing-list">{writing.map((item) => <Link href={`/writing/${item.slug}`} key={item.slug} className="writing-row"><div className="writing-meta"><span>{item.category}</span><span>{item.readTime}</span></div><h3>{item.title}</h3><p>{item.description}</p><time>{item.date}</time></Link>)}</div></div><aside className="exploring"><p className="eyebrow">03 / Currently exploring</p><h2>What has my attention now.</h2><div className="topic-cloud">{topics.map((topic) => <Link key={topic} href={`/topics/${topic.toLowerCase().replaceAll(" ", "-")}`}>{topic}</Link>)}</div><Link className="text-link" href="/now">See what I’m doing now <ArrowUpRight size={15} /></Link></aside></section>
  <section className="manifesto shell"><p className="eyebrow">Software · Cloud · Production</p><blockquote>From application code to systems teams can rely on.</blockquote><p>My experience spans SaaS development at Sycle.net, infrastructure and delivery automation at Global Relay, and platform engineering at HP. I work with architecture, security, and delivery teams to make systems easier to operate.</p></section>
  <section className="section shell lab-preview"><div className="section-heading"><p className="eyebrow">04 / From the lab</p><h2>Small bets and unfinished things.</h2><Link href="/projects">Enter the lab <ArrowUpRight size={15} /></Link></div><div className="project-grid">{projects.slice(0, 3).map((project) => <Link href="/projects" key={project.title} className="project-card"><span className="project-status">{project.status}</span><h3>{project.title}</h3><p>{project.summary}</p><small>{project.tech}</small></Link>)}</div><div className="latest-note"><span>{notes[0].date}</span><p>Latest note · <Link href="/notes">{notes[0].title}</Link></p></div></section>
</>; }
